// Smoke test: confirm buildTriangle matches the Python file's output for n=15.
// expected.txt is generated by pascals_triangle.py's algorithm, so this
// is the canonical regression guard.
import { readFileSync } from 'node:fs';
import { buildTriangle } from './src/lib/pascal.ts';

const expected = readFileSync(new URL('./expected.txt', import.meta.url), 'utf8')
  .replace(/\r/g, '')
  .trim()
  .split('\n');

const t = buildTriangle(15);

let pass = true;
for (let i = 0; i < 15; i++) {
  const got = '[' + t[i].map(String).join(',') + ']';
  if (got !== expected[i]) {
    console.error(`row ${i}: MISMATCH`);
    console.error(`  expected: ${expected[i]}`);
    console.error(`  got:      ${got}`);
    pass = false;
  }
}
console.log(pass ? 'OK: buildTriangle matches Python output for n=15' : 'FAIL');
process.exit(pass ? 0 : 1);
